<?php

namespace App\Application\Agents;

use App\Domain\Scene\Activity;

interface ChroniclerAgent
{
    /**
     * Resumes and records continuity advances for the given scene and generated text.
     *
     * @param Activity $scene
     * @param array<string, mixed> $context
     * @param string $generatedMd The text generated by the writer agent.
     * @param string $mode The generation mode (e.g. 'write_scene', 'rewrite_scene')
     * @return array<string, mixed>
     */
    public function generate(Activity $scene, array $context, string $generatedMd, string $mode): array;
}
